name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Usa a versão v2 para maior estabilidade

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable  # Garantindo que estamos usando a versão estável do Rust
          components: clippy, rustfmt  # Inclui clippy e rustfmt para análise e formatação

      - name: Ensure correct directory
        run: |
          echo "Current directory: $(pwd)"
          ls -la

      - name: Build project
        run: cargo build --verbose  # Garantir que estamos na pasta onde está o Cargo.toml

      - name: Run tests
        run: cargo test --verbose  # Executa os testes na raiz onde está o Cargo.toml
